[package]
name = "rpc-proxy"
version = "0.1.0"
edition = "2021"
authors = [
    "Derek <derek@walletconnect.com>"
]
build = "build.rs"


[features]
test-localhost = []

[dependencies]
# Async
async-trait = "0.1.57"
tokio = { version = "1", features = ["full"] }

# Web
hyper = "0.14.4"
hyper-tls = "0.5.0"
tap = "1.0"
warp = "0.3"
jsonrpc = "0.14.0"

# Serialization
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_piecewise_default = "0.2"
serde-aux = "3.1"

# Storage
aws-config = "0.47"
aws-sdk-s3 = "0.17"
deadpool-redis = "0.10"

dotenv = "0.15.0"
envy = "0.4"

anyhow = "1"
thiserror = "1.0"
derive_more = "0.99"
once_cell = "1.15"

ipnet = "2.5"
pnet_datalink = "0.31"

opentelemetry = { version = "0.17.0", features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-prometheus = "0.10.0"
prometheus-core = { package = "prometheus", version = "0.13" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "ansi"] }

cerberus = { git = "https://github.com/WalletConnect/cerberus.git", tag = "v0.1.2" }
gorgon = { git = "https://github.com/WalletConnect/gorgon.git", tag = "v0.2.0" }
parquet = { git = "https://github.com/WalletConnect/arrow-rs.git", rev = "431abf5", default-features = false, features = ["flate2"]  }
parquet_derive = { git = "https://github.com/WalletConnect/arrow-rs.git", rev = "431abf5" }
chrono = { version = "0.4", features = ["serde"] }


[dev-dependencies]
jsonrpc = "0.14.0"
test-context = "0.1"

[build-dependencies]
vergen = { version = "6", default-features = false, features = ["build", "cargo", "git"] }
